services:
  front:
    restart: always
    env_file:
      - .env
    build:
      context: ./front
      dockerfile: ./Dockerfile
    ports:
      - "19090:80"

  backend:
    restart: always
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8084:8000"
    command: /app/entrypoint.sh